DROP TABLE IF EXISTS TBL_WEATHER_REPORT;
 
CREATE TABLE TBL_WEATHER_REPORT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  temperature DECIMAL(14,9) NULL,
  wind_speed DECIMAL(14,9) NULL,
  humidity DECIMAL(14,9) NULL,
  date_time DATETIME
);